name = "ai-news-admin"
compatibility_date = "2024-07-19"
compatibility_flags = ["nodejs_compat_populate_process_env"]
pages_build_output_dir = "out"
[env.production.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://khpnsigvensxkxdntgqz.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocG5zaWd2ZW5zeGt4ZG50Z3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzQ2MDQsImV4cCI6MjA2ODI1MDYwNH0.3HAuhNTsKk6CzmhJ2X3tVgpP_BaRdXhFIwq3DxeCBVs"